version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          command: npm test
          name: Run test
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_build:
    jobs:
      - build_and_test