version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run: npm run test
      - run: npm run build

workflows:
  test_build:
    jobs: 
      - build_and_test