version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:21.6.1
      steps:
        - checkout
        - run:
            command: npm run test
            name: Run tests
        - run:
            command: npm run build
            name: Build app
        - persist_to_workspace:
            root: ~/project
            paths:
              - .
workflow:
  version: 2.1
  test_build:
    jobs:
      - build_and_test 